[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && mkdir -p dist/public && cp -r client/dist/* dist/public/"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "8080"
CORS_ORIGIN = "https://coffeetrackpro.railway.app"
DB_TYPE = "postgres"
SESSION_SECRET = "your_secure_session_secret_here"

[[services]]
name = "web"
port = 8080 