[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"
PORT = "5000"
SESSION_SECRET = "your-secure-session-secret"
CLIENT_URL = "https://your-client-url.com"

[[services]]
name = "web"
port = 8080 