[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "8080"
CORS_ORIGIN = "https://coffeetrackpro.railway.app"

[[services]]
name = "web"
port = 8080 