services:
  - type: web
    name: coffeetrackpro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://coffeetrackpro.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true 